server:
  error:
    include-stacktrace: never
  port: 8081

spring:
  application:
    name: CP Stars
  datasource:
    url: jdbc:postgresql://localhost:5432/cpstars
    username: cpstars
    password: cpstars
    driverClassName: org.postgresql.Driver
    hikari:
      minimum-idle: 2
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: none
  sql:
    init:
      platform: postgres

springdoc:
  api-docs:
    path: /openapi

paths:
  useResources: true
  # in case non-resource path should be used, below configuration is used instead to locate data
  files:
    spectra: files/spectra/
    lightCurves: files/light-curves/
