server:
  port: 8081

spring:
  application:
    name: CP Stars
  datasource:
    url: jdbc:postgresql://localhost:5432/cpstars
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
  sql:
    init:
      platform: postgres

springdoc:
  api-docs:
    path: /api/docs

paths:
  files:
    spectra: D:/Skola/diplomova-praca/spectra/
    lightCurves: D:\Skola\diplomova-praca\light-curves\
