server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cpstars
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      platform: postgres
